/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 TubeRack.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TubeRack(props) {
  const { nodes, materials } = useGLTF('/models/TubeRack.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry} material={materials['lambert2SG.001']} />
    </group>
  )
}

useGLTF.preload('/models/TubeRack.glb')
